version: "3"
services:
  rstudio:
    image: ${RSTUDIO_IMAGE}
    environment:
      USER: ${RSTUDIO_USER}
      PASSWORD: ${RSTUDIO_PASSWORD} 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      DB_PORT: ${DB_PORT}
    networks:
      - rstudio-pg
    ports:
      - ${RSTUDIO_PORT}:8787
    volumes:
      - rstudio_home:/home/rstudio
  db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRES_DB}
    ports: 
      - ${DB_PORT}:5432
    networks: 
      - rstudio-pg
    volumes:
      - pg_data:/bitnami/postgresql
volumes:
  rstudio_home:
  pg_data:
networks:
  rstudio-pg:

